version: "3.8"

services:
  inferno-dev:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: npx hardhat test
    tty: true
