import { BuilderConfig } from "./ConfigValidator";

const IFR_TOKEN_MAINNET = "0x77e99917Eca8539c62F509ED1193ac36580A6e7B";
const GOVERNANCE_MAINNET = "0xc43d48E7FDA576C5022d0670B652A622E8caD041";

export interface GeneratedCode {
  contractName: string;
  contractCode: string;
  sdkSnippet: string;
  deployGuide: string;
}

function sanitizeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, "") || "MyProduct";
}

export function generateCode(config: BuilderConfig): GeneratedCode {
  const safeName = sanitizeName(config.productName);
  const contractName = safeName + "Access";
  const date = new Date().toISOString().split("T")[0];

  // Determine modules
  const useHardLock = config.hardLock;
  const useTier = config.tierSystem;
  const useCooldown = config.cooldown;

  // Build imports
  const imports: string[] = [];
  if (useHardLock) {
    imports.push('import "./library/HardLockModule.sol";');
  } else {
    imports.push('import "./library/BaseAccessModule.sol";');
  }
  if (useTier) imports.push('import "./library/TierModule.sol";');
  if (useCooldown) imports.push('import "./library/CooldownModule.sol";');
  imports.push('import "@openzeppelin/contracts/access/Ownable.sol";');

  // Build inheritance
  const bases: string[] = [];
  if (useHardLock) bases.push("HardLockModule");
  else bases.push("BaseAccessModule");
  if (useTier) bases.push("TierModule");
  if (useCooldown) bases.push("CooldownModule");
  bases.push("Ownable");

  const minWei = config.minAmount * 1e9;
  const lockSecs = useHardLock ? config.lockDuration * 86400 : 0;
  const t1 = (config.tier1Amount || 500) * 1e9;
  const t2 = (config.tier2Amount || 2000) * 1e9;
  const t3 = (config.tier3Amount || 10000) * 1e9;

  // hasAccess override
  const hasAccessOverride = useHardLock
    ? `override(BaseAccessModule, HardLockModule)`
    : `override`;
  const hasAccessBody = useHardLock
    ? `HardLockModule.hasAccess(user)`
    : `BaseAccessModule.hasAccess(user)`;

  // Constructor body
  const ctorLines: string[] = [];
  if (useHardLock) ctorLines.push(`        minLockDuration = ${lockSecs}; // ${config.lockDuration} days`);
  if (useTier) {
    ctorLines.push(`        tier1Threshold = ${t1}; // ${config.tier1Amount || 500} IFR`);
    ctorLines.push(`        tier2Threshold = ${t2}; // ${config.tier2Amount || 2000} IFR`);
    ctorLines.push(`        tier3Threshold = ${t3}; // ${config.tier3Amount || 10000} IFR`);
  }
  if (useCooldown && config.cooldownHours && config.cooldownHours !== 24) {
    ctorLines.push(`        cooldownDuration = ${config.cooldownHours * 3600}; // ${config.cooldownHours}h`);
  }

  const tierMethods = useTier
    ? `
    /// @notice Get user tier (0=none, 1=basic, 2=premium, 3=pro)
    function getUserTier(address user) public view returns (uint8) {
        if (!hasAccess(user)) return 0;
        return getTier(user);
    }
`
    : "";

  const tierBalanceOverride = useTier && useHardLock
    ? `
    /// @notice Use locked balance for tier calculation
    function _tierBalance(address user) internal view override returns (uint256) {
        return locks[user].amount;
    }
`
    : "";

  const contractCode = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by IFR Integration Builder
// Product: ${config.productName}
// URL: ${config.productUrl}
// Date: ${date}
// Security: ${useHardLock && useCooldown && useTier ? "SAFE" : useHardLock || useTier ? "MEDIUM" : "RISKY"}

${imports.join("\n")}

contract ${contractName} is ${bases.join(", ")} {
    string public constant PRODUCT_NAME = "${config.productName}";
    string public constant PRODUCT_URL = "${config.productUrl}";

    constructor(address _governance)
        BaseAccessModule(${IFR_TOKEN_MAINNET}, ${minWei}) // ${config.minAmount} IFR
        Ownable(_governance)
    {
${ctorLines.join("\n")}
    }

    /// @notice Main access check — call this in your product
    function hasAccess(address user) public view ${hasAccessOverride} returns (bool) {
        return ${hasAccessBody};
    }
${tierBalanceOverride}${tierMethods}}
`;

  // SDK Snippet
  const sdkSnippet = `// npm install ifr-sdk
import { IFRClient } from "ifr-sdk";

const ifr = new IFRClient({ network: "mainnet" });

// Check access:
const hasAccess = await ifr.checkAccess({
  wallet: userAddress,
  required: ${config.minAmount}
});
${useTier ? `
// Tier check (1=basic, 2=premium, 3=pro):
const tier = await ifr.getTier(userAddress);
if (tier >= 2) enablePremiumFeatures();
if (tier >= 3) enableProFeatures();
` : ""}
if (hasAccess) enableAccess();
else showLockPrompt(${config.minAmount});

// REST API alternative:
// GET /api/ifr/check?wallet=0x...&required=${config.minAmount}`;

  // Deploy Guide
  const deployGuide = `# ${contractName} — Deployment Guide

## Prerequisites
- Hardhat project with OpenZeppelin v5
- IFR Contract Library (contracts/library/)
- Deployer wallet with ETH for gas

## Step 1: Deploy to Sepolia (test)
\`\`\`bash
npx hardhat run scripts/deploy.js --network sepolia
\`\`\`

## Step 2: Test access
- Lock ${config.minAmount} IFR → call hasAccess(wallet) → expect true
${useTier ? `- Lock 2000 IFR → call getUserTier(wallet) → expect 2` : ""}

## Step 3: Submit BuilderRegistry
Open issue: https://github.com/NeaBouli/inferno/issues/new
Label: builder-registry

## Step 4: Governance Proposal
setFeeExempt(${contractName}, true) — 48h timelock

## Step 5: Deploy to Mainnet
\`\`\`bash
npx hardhat run scripts/deploy.js --network mainnet
\`\`\`

## Step 6: Integrate SDK
\`\`\`bash
npm install ifr-sdk
\`\`\`

## Constructor Args
- _governance: ${GOVERNANCE_MAINNET}

## IFR Token
- Mainnet: ${IFR_TOKEN_MAINNET}
- Decimals: 9`;

  return { contractName, contractCode, sdkSnippet, deployGuide };
}
