// CWA-09 post-queue proof on a Mainnet fork pinned to exactly block 26119897: the generated step-2
// bytes are verified against the real queued proposals #19/#20 (exact target, calldata, ETA, pending
// state) and then executed by the Treasury Safe; afterwards all six mutable guardians are the Safe.
// Run: HARDHAT_FORK=true HARDHAT_FORK_BLOCK_NUMBER=26119897 MAINNET_RPC_URL=<archive rpc> npx hardhat test test/fork/GuardianQueuedExecutionFork.test.js
import { expect } from "chai";
import { createRequire } from "node:module";
import { ethers, connection } from "../helpers/hardhat.js";

const require = createRequire(import.meta.url);
const { buildVerifiedExecute, C, IMMUTABLE, TREASURY_SAFE, DEPLOYER, QUEUED_ETA } = require("../../scripts/guardian-migration-proposal.cjs");

async function impersonate(address) {
  await connection.provider.request({ method: "hardhat_impersonateAccount", params: [address] });
  await connection.provider.request({ method: "hardhat_setBalance", params: [address, "0xde0b6b3a7640000"] });
  return ethers.getSigner(address);
}
const QUEUE_EVIDENCE_BLOCK = 26119897; // read-only evidence: #19/#20 queued with the pinned content
const guardianOf = async (address) => (await ethers.getContractAt(["function guardian() view returns (address)"], address)).guardian();
const forkCall = (to, data) => ethers.provider.call({ to, data });

describe("Queued guardian proposals #19/#20 execute with the generated bytes on a Mainnet fork", function () {
  this.timeout(300_000);
  before(async function () {
    if (process.env.HARDHAT_FORK !== "true") this.skip();
    const block = await ethers.provider.getBlockNumber();
    expect(block, `fork must start at exactly QUEUE_EVIDENCE_BLOCK ${QUEUE_EVIDENCE_BLOCK}`).to.equal(QUEUE_EVIDENCE_BLOCK);
  });

  it("verifies the queued content, executes the generated bytes and moves the last two guardians", async () => {
    const governance = await ethers.getContractAt(
      ["function owner() view returns (address)", "function getProposal(uint256) view returns (address,bytes,uint256,bool,bool)"], C.Governance);
    const safe = await impersonate(await governance.owner());

    // Pre-state at the evidence block: steps 1-3 already ran live; only the two governed proposals are open.
    expect(await guardianOf(C.LiquidityReserve)).to.equal(DEPLOYER);
    expect(await guardianOf(C.BurnReserve)).to.equal(DEPLOYER);
    for (const address of [C.Governance, C.IFRLock, C.Vesting, C.PartnerVault]) {
      expect(await guardianOf(address)).to.equal(TREASURY_SAFE);
    }

    // Generation refuses any drift from the pinned queued proposals; only then are bytes produced.
    const files = await buildVerifiedExecute(forkCall);
    const step2 = files["guardian-step2-execute.json"].transactions;
    expect(step2.length).to.equal(2);
    expect(step2.every((t) => t.to === C.Governance && t.value === "0")).to.equal(true);

    await connection.provider.request({ method: "evm_setNextBlockTimestamp", params: [Number(QUEUED_ETA) + 1] });
    await connection.provider.request({ method: "evm_mine", params: [] });
    for (const t of step2) await safe.sendTransaction({ to: t.to, data: t.data, gasLimit: 500_000 });

    // All six mutable guardian postconditions hold; the immutable buyback guardians stay the deployer.
    for (const address of Object.values(C)) expect(await guardianOf(address)).to.equal(TREASURY_SAFE);
    for (const address of Object.values(IMMUTABLE)) expect(await guardianOf(address)).to.equal(DEPLOYER);
    for (const id of [19n, 20n]) {
      const [, , , executed, cancelled] = await governance.getProposal(id);
      expect(executed).to.equal(true);
      expect(cancelled).to.equal(false);
    }
  });

  it("refuses to generate against a block from before the proposals were queued (wrong fork block)", async () => {
    // Reads pinned at the pre-migration block 26108024 see no #19/#20; generation must refuse.
    const preQueueCall = (to, data) => ethers.provider.call({ to, data, blockTag: 26108024 });
    let refused = "";
    try {
      await buildVerifiedExecute(preQueueCall);
    } catch (error) {
      refused = error.message;
    }
    expect(refused).to.match(/proposal #19 does not exist/);
  });
});
