// Lane 3 decision B proof on a Mainnet fork pinned to exactly block 26119897 (CWA-02): the generated step-2
// bytes are verified against the real queued proposal #21 (exact target, calldata, ETA, pending state) and
// executed by the Treasury Safe; afterwards the 1% IFR pool fee reaches BuybackController instead of
// FeeRouterV1, a large IFR balance cannot block BuybackController.execute() (the controller is dormant; with
// much IFR against little ETH the LP add fails and the ETH falls back to buyback-and-burn), and Governance
// can recover IFR via withdrawIFR. IFR already stranded in FeeRouterV1 is not touched: FeeRouterV1 has no
// sweep and this proof does not claim any automatic liquidity or recovery for those funds.
// Run: HARDHAT_FORK=true HARDHAT_FORK_BLOCK_NUMBER=26119897 MAINNET_RPC_URL=<archive rpc> npx hardhat test test/fork/PoolFeeReceiverFork.test.js
import { expect } from "chai";
import { createRequire } from "node:module";
import { ethers, connection } from "../helpers/hardhat.js";

const require = createRequire(import.meta.url);
const { buildVerifiedExecute, IFR_TOKEN, GOVERNANCE, BUYBACK_CONTROLLER, FEE_ROUTER_V1, QUEUED_ETA } = require("../../scripts/pool-fee-receiver-proposal.cjs");
const LIQUIDITY_RESERVE = "0xdc0309804803b3A105154f6073061E3185018f64"; // fee-exempt IFR source, fork only
const parse = (s) => ethers.parseUnits(s, 9);

async function impersonate(address) {
  await connection.provider.request({ method: "hardhat_impersonateAccount", params: [address] });
  await connection.provider.request({ method: "hardhat_setBalance", params: [address, "0x56bc75e2d63100000"] });
  return ethers.getSigner(address);
}
const QUEUE_EVIDENCE_BLOCK = 26119897; // read-only evidence: #21 queued with the pinned content
const forkCall = (to, data) => ethers.provider.call({ to, data });

describe("Queued pool fee receiver proposal #21 executes with the generated bytes on a Mainnet fork", function () {
  this.timeout(300_000);
  before(async function () {
    if (process.env.HARDHAT_FORK !== "true") this.skip();
    const block = await ethers.provider.getBlockNumber();
    expect(block, `fork must start at exactly QUEUE_EVIDENCE_BLOCK ${QUEUE_EVIDENCE_BLOCK}`).to.equal(QUEUE_EVIDENCE_BLOCK);
  });

  it("verifies the queued content, executes #21, routes fees to BuybackController; Governance can withdraw", async () => {
    const token = await ethers.getContractAt(
      ["function poolFeeReceiver() view returns (address)", "function balanceOf(address) view returns (uint256)",
       "function transfer(address,uint256) returns (bool)", "function poolFeeBps() view returns (uint256)"], IFR_TOKEN);
    const governance = await ethers.getContractAt(
      ["function owner() view returns (address)", "function getProposal(uint256) view returns (address,bytes,uint256,bool,bool)"], GOVERNANCE);
    const controller = await ethers.getContractAt(
      ["function execute()", "function cooldown() view returns (uint256)", "function lastExecution() view returns (uint256)",
       "function minTriggerAmount() view returns (uint256)", "function paused() view returns (bool)",
       "function withdrawIFR(address,uint256)"], BUYBACK_CONTROLLER);
    expect(await token.poolFeeReceiver()).to.equal(FEE_ROUTER_V1);

    const safe = await impersonate(await governance.owner());

    // Generation refuses any drift from the pinned queued proposal; only then are bytes produced.
    const files = await buildVerifiedExecute(forkCall);
    const step2 = files["lane3-poolfee-step2-execute.json"].transactions[0];
    expect(step2.to).to.equal(GOVERNANCE);
    expect(step2.value).to.equal("0");

    await connection.provider.request({ method: "evm_setNextBlockTimestamp", params: [Number(QUEUED_ETA) + 1] });
    await connection.provider.request({ method: "evm_mine", params: [] });
    await safe.sendTransaction({ to: step2.to, data: step2.data, gasLimit: 500_000 });
    expect(await token.poolFeeReceiver()).to.equal(BUYBACK_CONTROLLER);
    const [, , , executed, cancelled] = await governance.getProposal(21n);
    expect(executed).to.equal(true);
    expect(cancelled).to.equal(false);

    // A non-exempt transfer now pays the pool fee to BuybackController; FeeRouterV1 stops growing.
    const [alice, bob] = await ethers.getSigners();
    const reserve = await impersonate(LIQUIDITY_RESERVE);
    await token.connect(reserve).transfer(alice.address, parse("1000000"));
    const routerBefore = await token.balanceOf(FEE_ROUTER_V1);
    const controllerBefore = await token.balanceOf(BUYBACK_CONTROLLER);
    await token.connect(alice).transfer(bob.address, parse("500000"));
    const fee = (parse("500000") * (await token.poolFeeBps())) / 10_000n;
    expect((await token.balanceOf(BUYBACK_CONTROLLER)) - controllerBefore).to.equal(fee);
    expect(await token.balanceOf(FEE_ROUTER_V1)).to.equal(routerBefore);

    // A large IFR balance must not block the permissionless buyback cycle (LP failure falls back to burn).
    if (!(await controller.paused())) {
      const funder = await impersonate("0x000000000000000000000000000000000000dEaD");
      const trigger = await controller.minTriggerAmount();
      await funder.sendTransaction({ to: BUYBACK_CONTROLLER, value: trigger > 0n ? trigger : ethers.parseEther("0.01") });
      const wait = Number((await controller.lastExecution()) + (await controller.cooldown()));
      const now = (await ethers.provider.getBlock("latest")).timestamp;
      if (wait > now) {
        await connection.provider.request({ method: "evm_setNextBlockTimestamp", params: [wait + 1] });
        await connection.provider.request({ method: "evm_mine", params: [] });
      }
      await controller.connect(bob).execute();
    }

    // Governance (owner) can recover accrued IFR.
    const gov = await impersonate(GOVERNANCE);
    const held = await token.balanceOf(BUYBACK_CONTROLLER);
    expect(held).to.be.greaterThan(0n);
    await controller.connect(gov).withdrawIFR(LIQUIDITY_RESERVE, held);
    expect(await token.balanceOf(BUYBACK_CONTROLLER)).to.equal(0n);
  });

  it("refuses to generate against a block from before the proposal was queued (wrong fork block)", async () => {
    // Reads pinned at the pre-queue block 26108024 see no #21; generation must refuse.
    const preQueueCall = (to, data) => ethers.provider.call({ to, data, blockTag: 26108024 });
    let refused = "";
    try {
      await buildVerifiedExecute(preQueueCall);
    } catch (error) {
      refused = error.message;
    }
    expect(refused).to.match(/proposal #21 does not exist/);
  });
});
