export const InfernoTokenABI = [
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function decimals() view returns (uint8)",
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function feeExempt(address) view returns (bool)",
  "function senderBurnBps() view returns (uint256)",
  "function recipientBurnBps() view returns (uint256)",
  "function poolFeeBps() view returns (uint256)",
  "function owner() view returns (address)",
  "function setFeeExempt(address account, bool exempt)",
  "function setFeeRates(uint256 senderBurn, uint256 recipientBurn, uint256 poolFee)",
];

export const IFRLockABI = [
  "function totalLocked() view returns (uint256)",
  "function lockedBalance(address user) view returns (uint256)",
  "function isLocked(address user, uint256 minAmount) view returns (bool)",
  "function lockInfo(address user) view returns (uint256 amount, uint256 lockedAt)",
  "function token() view returns (address)",
  "function guardian() view returns (address)",
  "function paused() view returns (bool)",
  "event Locked(address indexed user, uint256 amount, bytes32 indexed lockType)",
  "event Unlocked(address indexed user, uint256 amount)",
];

export const PartnerVaultABI = [
  "function ifrToken() view returns (address)",
  "function admin() view returns (address)",
  "function guardian() view returns (address)",
  "function ifrLock() view returns (address)",
  "function PARTNER_POOL() view returns (uint256)",
  "function TOTAL_SUPPLY() view returns (uint256)",
  "function rewardBps() view returns (uint256)",
  "function MIN_REWARD_BPS() view returns (uint256)",
  "function MAX_REWARD_BPS() view returns (uint256)",
  "function annualEmissionCap() view returns (uint256)",
  "function MIN_ANNUAL_CAP() view returns (uint256)",
  "function MAX_ANNUAL_CAP() view returns (uint256)",
  "function totalAllocated() view returns (uint256)",
  "function totalRewarded() view returns (uint256)",
  "function totalClaimed() view returns (uint256)",
  "function yearStart() view returns (uint256)",
  "function yearlyEmitted() view returns (uint256)",
  "function authorizedCaller(address) view returns (bool)",
  "function walletRewardClaimed(address, bytes32) view returns (bool)",
  "function partners(bytes32) view returns (address beneficiary, uint256 maxAllocation, uint256 unlockedTotal, uint256 rewardAccrued, uint256 claimedTotal, uint32 vestingStart, uint32 vestingDuration, uint32 cliff, bool active, bool milestonesFinal, uint8 tier)",
  "function claimable(bytes32) view returns (uint256)",
  "function vestedAmount(bytes32) view returns (uint256)",
  "function pendingBalance() view returns (uint256)",
  "function milestoneDone(bytes32, bytes32) view returns (bool)",
  "function setRewardBps(uint256 newBps)",
  "function setAnnualEmissionCap(uint256 newCap)",
  "function setAuthorizedCaller(address caller, bool status)",
  "function setIFRLock(address _ifrLock)",
  "function createPartner(bytes32 partnerId, address beneficiary, uint256 maxAllocation, uint32 vestingDuration, uint32 cliff, uint8 tier)",
  "function activatePartner(bytes32 partnerId)",
  "function recordMilestone(bytes32 partnerId, bytes32 milestoneId, uint256 unlockAmount)",
  "event PartnerCreated(bytes32 indexed partnerId, address beneficiary, uint256 maxAllocation, uint32 vestingDuration, uint32 cliff, uint8 tier)",
  "event PartnerActivated(bytes32 indexed partnerId)",
  "event MilestoneRecorded(bytes32 indexed partnerId, bytes32 indexed milestoneId, uint256 unlockAmount)",
  "event LockRewardRecorded(bytes32 indexed partnerId, address indexed wallet, uint256 lockAmount, uint256 reward)",
  "event Claimed(bytes32 indexed partnerId, address indexed beneficiary, uint256 amount)",
  "event RewardBpsUpdated(uint256 oldBps, uint256 newBps)",
  "event AnnualCapUpdated(uint256 oldCap, uint256 newCap)",
  "event AuthorizedCallerUpdated(address indexed caller, bool status)",
  "event IFRLockUpdated(address indexed oldLock, address indexed newLock)",
];

export const GovernanceABI = [
  "function proposalCount() view returns (uint256)",
  "function getProposal(uint256) view returns (address target, bytes data, uint256 eta, bool executed, bool cancelled)",
  "function delay() view returns (uint256)",
  "function owner() view returns (address)",
  "function guardian() view returns (address)",
  "function MIN_DELAY() view returns (uint256)",
  "function MAX_DELAY() view returns (uint256)",
  "function propose(address target, bytes data) returns (uint256)",
  "function execute(uint256 proposalId)",
  "function cancel(uint256 proposalId)",
  "event ProposalCreated(uint256 indexed proposalId, address indexed target, bytes data, uint256 eta)",
  "event ProposalExecuted(uint256 indexed proposalId)",
  "event ProposalCancelled(uint256 indexed proposalId)",
];
